basePath: /
definitions:
  big.Int:
    type: object
  controller.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  model.Group:
    properties:
      indexes:
        items:
          $ref: '#/definitions/big.Int'
        type: array
      name:
        type: string
    type: object
  model.Index:
    properties:
      ethpriceinwei:
        $ref: '#/definitions/big.Int'
      name:
        type: string
      percentagechange:
        $ref: '#/definitions/big.Int'
      usdcapitalization:
        $ref: '#/definitions/big.Int'
      usdpriceincents:
        $ref: '#/definitions/big.Int'
    type: object
  types.Header:
    properties:
      baseFeePerGas:
        $ref: '#/definitions/big.Int'
        description: BaseFee was added by EIP-1559 and is ignored in legacy headers.
      difficulty:
        $ref: '#/definitions/big.Int'
      extraData:
        items:
          type: integer
        type: array
      gasLimit:
        type: integer
      gasUsed:
        type: integer
      logsBloom:
        items:
          type: integer
        type: array
      miner:
        items:
          type: integer
        type: array
      mixHash:
        items:
          type: integer
        type: array
      nonce:
        items:
          type: integer
        type: array
      number:
        $ref: '#/definitions/big.Int'
      parentHash:
        items:
          type: integer
        type: array
      receiptsRoot:
        items:
          type: integer
        type: array
      sha3Uncles:
        items:
          type: integer
        type: array
      stateRoot:
        items:
          type: integer
        type: array
      timestamp:
        type: integer
      transactionsRoot:
        items:
          type: integer
        type: array
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a server to get information from smart contract 0x4f7f1380239450AAD5af611DB3c3c1bb51049c29
    and general block information.
  title: Ethereum smart contract API
  version: "1.0"
paths:
  /:
    get:
      description: Root path to give hint about available methods
      summary: Show possible API routes
  /blocks/{blockParameter}:
    get:
      consumes:
      - application/json
      description: get all header information of the block
      parameters:
      - description: blockNumber/blockHash/latest
        in: path
        name: blockParameter
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Header'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get block's header information
  /groups:
    get:
      consumes:
      - application/json
      description: get all groups in smart contract
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/big.Int'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get groups
  /groups/{groupId}:
    get:
      consumes:
      - application/json
      description: get detail information of specific group
      parameters:
      - description: Group ID
        in: path
        name: groupId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Group'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get group's information
  /indexes/{indexId}:
    get:
      consumes:
      - application/json
      description: get detail information of specific index
      parameters:
      - description: Index ID
        in: path
        name: indexId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Index'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: Get index's information
securityDefinitions:
  not used in current API's version:
    type: basic
swagger: "2.0"
